import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "page 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-[90vh] flex flex-col items-center justify-center bg-gray-100 text-gray-900 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
